[package]
name = "led_matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.22.1"

[build.env]
passthrough = [
    "CROSS_CONTAINER_ENGINE",
]

